package net.modding.util;

import net.minecraft.client.Minecraft;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.modding.main.modding;

public class McMod_info extends modding{

	public static String mcVersion;
	public static String Beschreibung;
	public static final String AUTOR_1 = "Joel Kuhle";
	public static final String FILE = "";
	public static final String CREDITS = "Joel Kuhle for coding this mod, MikasOrbit for making the tutorials and the team from Though as nails mod for shareing their sourcecode. I have copied some declared methods from that mod.";
	public static final String DOWNLOAD_URL = "https://goo.gl/FyOeAg";
	public static final String UPDATE_URL = "https://goo.gl/YPKlEl";
	public static final String LOGO_ORT = "ferro_chestplate.png";
	
	public void ModData(FMLPreInitializationEvent preInit) {
		mcVersion = MinecraftForge.MC_VERSION;
		Beschreibung = "This is a cool mod, with which you can alloy your Armor, Tools and Swords. It was made for Minecraft Version " + mcVersion + ".";
		ModMetadata data = preInit.getModMetadata();
		data.autogenerated = false;
		data.modId = modding.MODID;
		data.name = modding.NAME;
		data.version = modding.VERSION;
		data.url = DOWNLOAD_URL;
		data.updateUrl = UPDATE_URL;
		data.authorList.add(AUTOR_1);
		data.description = Beschreibung;
		data.credits = CREDITS;
		data.logoFile = LOGO_ORT;
		
	}

}
